services:
  x-scheduler:
    build: .
    container_name: x-post-scheduler
    restart: unless-stopped
    tty: true
    ports:
      - "8002:8002"
    env_file:
      - .env

    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./media:/app/media
